version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9.29
    ports:
      - 5672:5672  # AMQP 포트
      - 15672:15672  # 관리자 인터페이스 포트
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

volumes:
  rabbitmq_data:
